[Lat_fins(~finished), Lon_fins(~finished,:), ...
    Lat_hs(~finished,:), Lon_hs(~finished,:)] = update_loc_hrly(...
    fl_hrs(~finished),hourly_del_Lat, ...
    curr_dep_Lat(~finished),curr_dep_Lon(~finished), ...
    alpha(~finished),N_S_migr, ...
    tail_w(~finished), cross_w(~finished),magn_star_night, ...
    decln(~finished),date_jul(~finished),geomagn_model);


[ahead_theta, ahead_llamda] = update_loc(...
            fl_hrs(~finished),hourly_del_Lat,theta(~finished), ...
            llamda(~finished),alpha(~finished),N_S_migr, ...
            u_wind(~finished),v_wind(~finished), ...
            star_cmp_flag,decln(~finished),date_jul(~finished),geomagn_model);

diffLL = sqrt((mod(Lon_fins(~finished),2*pi)-mod(ahead_llamda,2*pi)).^2 ...
    +(Lat_fins(~finished)-ahead_theta).^2);


% figure; scatter(mod(ahead_llamda,2*pi),ahead_theta,30, ...
%     diffLL,'fill'); colorbar



figure; scatter(mod(Lon_fins(~finished),2*pi),Lat_fins(~finished),30, ...
    diffLL,'fill'); colorbar

id_mxs = find(diffLL > 0.25,4,'first');

figure;
scatter(curr_dep_Lon(id_mxs)*180/pi,curr_dep_Lat(id_mxs)*180/pi, ...
    30,alpha(id_mxs)*180/pi,'fill'); colorbar

figure;
scatter(Lon_fins(id_mxs)*180/pi, Lat_fins(id_mxs)*180/pi, ...
    30,alpha(id_mxs)*180/pi,'fill'); colorbar

d_trav = sqrt((mod(Lon_fins(~finished),2*pi)- ...
    mod(curr_dep_Lon,2*pi)).^2.*cos(curr_dep_Lat) ...
    +(Lat_fins(~finished)-curr_dep_Lat).^2);

figure; histogram(d_trav)

azimuth(curr_dep_Lat(1)*180/pi,curr_dep_Lon(1)*180/pi, ...
    Lat_fins(1)*180/pi,Lon_fins(1)*180/pi)

atan2d(u_wind(1),v_wind(1))

